"""Change hour column to DateTime

Revision ID: 0980b0afdce7
Revises: 2276ff2127c6
Create Date: 2023-12-13 08:59:52.117284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0980b0afdce7'
down_revision = '2276ff2127c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_price', schema=None) as batch_op:
        batch_op.alter_column('hour',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_price', schema=None) as batch_op:
        batch_op.alter_column('hour',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
