"""Add Zip code to registration

Revision ID: 2276ff2127c6
Revises: 4af539e36e40
Create Date: 2023-12-11 11:30:47.594196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2276ff2127c6'
down_revision = '4af539e36e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=True))

    # Update existing records with a valid zip code
    op.execute("UPDATE user SET zip_code = 'default_zip_code' WHERE zip_code IS NULL")

    # Change the column to be non-nullable
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('zip_code', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
